version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/usr/src/app
    ports:
      - '7000:7000'

#     depends_on:
#       - pgdb
  
#   pgdb:
#       image: postgres
#       container_name: pgdb
#       environment:
#              - POSTGRES_DB=docker_db
#              - POSTGRES_USER=postgres
#              - POSTGRES_PASSWORD=nodejs12
#       volumes:
#              - pgdata:/var/lib/postgresql/data/

# volumes:
#     pgdata: