version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - pgdb
    networks:
      - djangonetwork
  
  pgdb:
      image: postgres
      container_name: pgdb
      networks:
          - djangonetwork
      environment:
             - POSTGRES_DB=customer_orders_db
             - POSTGRES_USER=postgres
             - POSTGRES_PASSWORD=nodejs12
      volumes:
             - pgdata:/var/lib/postgresql/data/
      restart: always
      expose:
        - "5432"
      ports:
        - "5432:5432"

volumes:
    pgdata:
networks:
  djangonetwork:
    driver: bridge