# Generated by Django 5.0.2 on 2024-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
